# Read the documentation: https://symfony.com/doc/master/bundles/FOSRestBundle/index.html
fos_rest:
  body_listener: true
  param_fetcher_listener: true
  format_listener:
    rules:
      - { path: '^/', priorities: ['json','html'], fallback_format: json, prefer_extension: false }